#!/util/academic/R/R-3.0.0/bin/Rscript
#
documentation <- "
 A script to visualize the results of a kmeans clustering generated by 
 kmeans.slurm.

 Usage: R/vizKmeansResults.R DATA_FILE_NAME JOBID RUNID

 Input arguments:
 [1] DATA_FILE_NAME, the path and filename of the input csv file that was
     clustered.
 [2] JOBID, the integer number of the SLURM job
 [3] RUNID, the integer number of the run to visualize
"

library(MASS) # for ginv()

# get input arguments
argIn <- commandArgs(TRUE)
if (length(argIn) < 3) {
  writeLines('\n Not enough input arguments supplied!')
  writeLines(documentation)
  stop('Exiting')
}
DATA_FILE_NAME <- argIn[1]
JOBID <- argIn[2]
RUNID <- argIn[3]

# Name of folder for output
saveDirName <- 'summary'

# get directory structure, cluster centroid
centroidFileNames <- list.files(
  file.path(paste('myoutput-',JOBID,sep=''),paste('run_',RUNID,sep='')),
  pattern='currentMeans_i',
  recursive=TRUE,
  full.names=TRUE
)

centroidFileNames <- as.vector(centroidFileNames)
cat('Before sorting:\n')
print(centroidFileNames)

# Sort in _numeric_ order
centroidFileNames <- centroidFileNames[order(nchar(centroidFileNames), centroidFileNames)]
cat('\nAfter sorting:\n')
print(centroidFileNames)

# Read in full data and rescale
dat <- read.csv(DATA_FILE_NAME,header=TRUE)
datMeans <- colMeans(dat)
datSds <- apply(dat,2,sd)
datSds[datSds==0] <- 1 # for cols with no variance
dat <- scale(dat, center=datMeans, scale=datSds)

# plot first two PCs
# X = U %*% D %*% V'
# U = X %*% solve(D %*% V')
svdDat <- svd(dat)
transMat <- ginv(diag(svdDat$d) %*% t(svdDat$v))
#print('str(dat)')
#print(str(dat))
#print('dim(transMat)')
#print(dim(transMat))

# Read in all centroid data and rescale
allCentroids <- lapply(
  centroidFileNames,
  FUN=function(ff) {
    load(ff)
    dd=t(as.data.frame(myMeans)) 
    dd <- scale(dd, center=datMeans, scale=datSds)
    rownames(dd) <- paste('Clust',1:nrow(dd))
    colnames(dd) <- paste('Dim',1:ncol(dd))
    return(dd)
  }
)
#print(allCentroids)
numIter <- length(allCentroids)
numClust <- nrow(allCentroids[[1]])

# distinct colors for the clusters
myColors <- rainbow(numClust)
myColorsAlpha <- rainbow(numClust,alpha=0.5)

# Color points by nearest cluster
# Inefficient implementation: fix this
datColors <- t(apply(
  dat,
  1,
  function(rr) which.min(as.matrix(dist(rbind(rr,allCentroids[[numIter]])))[-1,1])
))

# create image file
suppressWarnings(dir.create(saveDirName))
plotName <- paste('kmeansPlot_',JOBID,'.png',sep='')
png(file=file.path(saveDirName,plotName))
plot(
  dat %*% transMat,
  xlab='Principal Component 1',
  ylab='Principal Component 2',
  col = myColorsAlpha[datColors]
)

for (i in 1:numIter) {
  transCentroids <- allCentroids[[i]] %*% transMat
  points(transCentroids, pch=19, col=myColors, cex=2.5)
  points(transCentroids, pch=1, col='black', cex=2.5, lwd=2)
  text(transCentroids, labels=i,cex=0.8)
}

png()

